services:
  - type: web
    name: tssezl-api
    env: node
    rootDir: backend
    buildCommand: |
      cd ../invoice-frontend
      npm ci --production=false
      npm run build
      cd ../backend
      npm ci --production
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://parthkumar157:P@rth157@cluster0.vkbn5fk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: yourSecretKey
      - key: NODE_ENV
        value: production
