services:
  - type: web
    name: tssezl-app
    env: node
    plan: free
    buildCommand: |
      cd invoice-frontend && npm install && npm run build
      cd ../backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        value: <your-uri>
      - key: JWT_SECRET
        value: yourSecretKey
      - key: NODE_ENV
        value: production
